const express = require('express');
const mongoose = require('mongoose');
const multer = require('multer');
const cors = require('cors');
const { GridFSBucket } = require('mongodb');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(express.json({ limit: '50mb' })); // Allow large base64 covers

// MongoDB Connection (Railway will provide process.env.MONGO_URL)
const mongoURI = process.env.MONGO_URL || 'mongodb://localhost:27017/nixuvik';
mongoose.connect(mongoURI);
const conn = mongoose.connection;

let gfsBucket;
conn.once('open', () => {
    console.log('Connected to MongoDB');
    gfsBucket = new GridFSBucket(conn.db, { bucketName: 'books' });
});

// Multer storage (Memory Storage to pass buffer directly to GridFS)
const storage = multer.memoryStorage();
const upload = multer({ 
    storage: storage, 
    limits: { fileSize: 55 * 1024 * 1024 } // 55MB Limit
});

// Book Metadata Schema
const BookSchema = new mongoose.Schema({
    title: String,
    size: Number,
    uploadDate: { type: Date, default: Date.now },
    cover: String, // Base64 image generated by PDF.js on the frontend
    fileId: mongoose.Schema.Types.ObjectId // Reference to the actual PDF file in GridFS
});
const Book = mongoose.model('Book', BookSchema);

// --- API ENDPOINTS ---

// 1. Upload a Book (File + Cover)
app.post('/api/books', upload.single('file'), async (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ error: 'No file uploaded' });

        const file = req.file;
        const cover = req.body.cover; 
        
        // Upload the massive file buffer to MongoDB GridFS stream
        const uploadStream = gfsBucket.openUploadStream(file.originalname, {
            contentType: file.mimetype
        });
        uploadStream.end(file.buffer);

        uploadStream.on('finish', async () => {
            // Save the metadata pointing to the GridFS file
            const newBook = new Book({
                title: file.originalname,
                size: file.size,
                cover: cover,
                fileId: uploadStream.id
            });
            await newBook.save();
            res.status(201).json(newBook);
        });

        uploadStream.on('error', (err) => {
            res.status(500).json({ error: 'Error uploading file to GridFS' });
        });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// 2. Get all Books (Metadata + Covers for the Video Grid)
app.get('/api/books', async (req, res) => {
    try {
        const books = await Book.find().sort({ uploadDate: -1 });
        res.json(books);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// 3. Download/View Book File
app.get('/api/books/:id/download', async (req, res) => {
    try {
        const book = await Book.findById(req.params.id);
        if (!book) return res.status(404).send('Book not found');
        
        res.set('Content-Type', 'application/pdf');
        res.set('Content-Disposition', `inline; filename="${book.title}"`);
        
        gfsBucket.openDownloadStream(book.fileId).pipe(res);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// 4. Delete Book
app.delete('/api/books/:id', async (req, res) => {
    try {
        const book = await Book.findById(req.params.id);
        if (!book) return res.status(404).json({ error: 'Book not found' });

        await gfsBucket.delete(book.fileId);
        await Book.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Fallback to serving index.html if you decide to host the frontend via Express as well
app.get('/', (req, res) => {
    res.send('NIXUVIK API is running. Point your index.html RAILWAY_URL to this domain!');
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});